from dateutil.tz import gettz

# サイト設定
SITE_CONFIG = {
    "PHP Security Releases": {
        "method": "beautifulsoup",
        "url": "https://www.php.net/archive/2025.php",
        "selectors": {
            "rows": "article.newsItem",
            "date": "time.newsdate",
            "title": "h2.newstitle a",
            "link": "h2.newstitle a[href]",
            "description": "div.newscontent",
        },
        "date_formats": ["%d %b %Y"],
        "max_entries": 10,
        "filter_description_keywords": ["security release", "security fix"],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "Apache Tomcat 11 Security Advisories": {
        "method": "beautifulsoup",
        "url": "https://tomcat.apache.org/security-11.html",
        "selectors": {
            "rows": "h3[id]",
            "date": "span.pull-right",
            "title": "h3[id]",
            "link": "h3[id]",
            "cve": "div.text a[href*='cve.mitre.org']",
        },
        "date_formats": ["%Y-%m-%d"],
        "max_entries": 10,
        "remove_words": [],
    },
    "Apache Tomcat 10 Security Advisories": {
        "method": "beautifulsoup",
        "url": "https://tomcat.apache.org/security-10.html",
        "selectors": {
            "rows": "h3[id]",
            "date": "span.pull-right",
            "title": "h3[id]",
            "link": "h3[id]",
            "cve": "div.text a[href*='cve.mitre.org']",
        },
        "date_formats": ["%Y-%m-%d"],
        "max_entries": 10,
        "remove_words": [],
    },
    "Apache Tomcat 9 Security Advisories": {
        "method": "beautifulsoup",
        "url": "https://tomcat.apache.org/security-9.html",
        "selectors": {
            "rows": "h3[id]",
            "date": "span.pull-right",
            "title": "h3[id]",
            "link": "h3[id]",
            "cve": "div.text a[href*='cve.mitre.org']",
        },
        "date_formats": ["%Y-%m-%d"],
        "max_entries": 10,
        "remove_words": [],
    },
    "一太郎": {
        "method": "selenium",
        "url": "https://www.justsystems.com/jp/corporate/info/?category=%E3%82%BB%E3%82%AD%E3%83%A5%E3%83%AA%E3%83%86%E3%82%A3%E6%83%85%E5%A0%B1",
        "Xpath": {
            "article": "//li[contains(@class, 'info-list__item')]",
            "title": ".//p[contains(@class, 'info-txt')]",
            "link": ".//a[@href]",
            "date": ".//p[contains(@class, 'info-day')]",
        },
        "date_formats": ["%y.%m.%d"],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "Citrix": {
        "method": "selenium",
        "url": "https://support.citrix.com/s/topic/0TO4z0000001GYdGAM/security-bulletin?language=en_US",
        "Xpath": {
            "article": "//li[contains(@class, 'article-item')]",
            "title": ".//h2[contains(@class, 'article-head')]",
            "link": ".//a[contains(@class, 'article-link')]",
            "date": ".//span[contains(@class, 'uiOutputDate')]",
        },
        "date_formats": ["%Y/%m/%d"],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "Cisco": {
        "method": "selenium",
        "url": "https://sec.cloudapps.cisco.com/security/center/publicationListing.x",
        "Xpath": {
            "article": "//tr[@ng-repeat='list in advisoryList']",
            "title": ".//a[@class='ng-binding']",
            "link": ".//a[@class='ng-binding'][@href]",
            "date": ".//td[4]/span[contains(@class, 'ng-binding')]",
        },
        "date_formats": [],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "Juniper": {
        "method": "selenium",
        "url": "https://supportportal.juniper.net/s/global-search/%40uri?language=en_US#sort=%40sfcec_community_publish_date_formula__c%20descending&numberOfResults=25&f:ctype=[Security%20Advisories]",
        "Xpath": {
            "article": "//div[contains(@class, 'coveo-list-layout CoveoResult')]",
            "title": ".//a[contains(@class, 'CoveoResultLink')]",
            "link": ".//a[contains(@class, 'CoveoResultLink')]",
            "date": ".//span[contains(@data-helper, 'publishdate')]/span",
        },
        "date_formats": ["%Y-%m-%d"],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "Broadcom VMware": {
        "method": "selenium",
        "url": "https://support.broadcom.com/web/ecx/search?searchString=VMware+%26%26+vulnerabilities&activeType=server_notifications&from=0&sortby=post_time&orderBy=desc&pageNo=1&aggregations=%5B%7B%22type%22%3A%22_index%22%2C%22filter%22%3A%5B%22server_notifications%22%5D%7D%5D&uid=d042dbba-f8c4-11ea-beba-0242ac12000b&resultsPerPage=10&exactPhrase=&withOneOrMore=&withoutTheWords=&pageSize=10&language=en&state=1&suCaseCreate=false",
        "Xpath": {
            "article": "//div[contains(@class, 'su__list-items')]",
            "title": ".//h2",
            "link": ".//a",
            "date": './/span[contains(@class, "su__tags") and contains(text(), "/")]',
        },
        "date_formats": ["%m/%d/%Y %I:%M %p", "%m/%d/%Y"],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    # # 古い記事ßのみ
    "Broadcom Symantec": {
        "method": "selenium",
        "url": "https://support.broadcom.com/web/ecx/search?searchString=%28%22Symantec+Endpoint+Protection%22+%7C%7C+%22Symantec+Anti-Virus+Engine%22%29+%26%26+vulnerabilities&activeType=server_notifications&from=0&sortby=post_time&orderBy=desc&pageNo=1&aggregations=%5B%7B%22type%22%3A%22_index%22%2C%22filter%22%3A%5B%22server_notifications%22%5D%7D%5D&uid=d042dbba-f8c4-11ea-beba-0242ac12000b&resultsPerPage=10&exactPhrase=&withOneOrMore=&withoutTheWords=&pageSize=10&language=en&state=1&suCaseCreate=false",
        "Xpath": {
            "article": "//div[contains(@class, 'su__list-items')]",
            "title": ".//h2",
            "link": ".//a",
            "date": './/span[contains(@class, "su__tags") and contains(text(), "/")]',
        },
        "date_formats": ["%m/%d/%Y %I:%M %p", "%m/%d/%Y"],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "ESET": {
        "method": "selenium",
        "url": "https://support-feed.eset.com/advisories/",
        "Xpath": {
            "article": "//li[@class='regularitem']",
            "title": ".//h4[@class='itemtitle']/a",
            "link": ".//h4[@class='itemtitle']/a",
            "date": ".//span[@class='itemposttime-data']",
            "description": ".//div[@class='itemcontent']",
        },
        "max_entries": 10,
        "date_formats": ["%A, %B %d, %Y %I:%M %p"],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "Adobe Acrobat and Reader": {
        "method": "beautifulsoup",
        "url": "https://helpx.adobe.com/security/security-bulletin.html#acrobat",
        "selectors": {
            "rows": "table tbody tr",
            "title": "td:nth-child(1) a",
            "link": "td:nth-child(1) a[href]",
            "date": "td:nth-child(2)",
        },
        "date_formats": ["%m/%d/%Y", "%m/%d/%y"],
        "filter_description_keywords": [],
        "filter_title_keywords": [
            "Adobe Reader",
            "Acrobat Reader",
            "Adobe Acrobat and Reader",
        ],
        "remove_words": [],
    },
    "SAP": {
        "method": "beautifulsoup",
        "url": "https://support.sap.com/en/my-support/knowledge-base/security-notes-news.html",
        "selectors": {
            "rows": "div.panel-1dx-blue .text-editor p b a",
            "title": None,
            "link": None,
            "date": None,
        },
        "date_formats": ["%B %d"],
        "remove_words": [],
    },
    "netgear": {
        "method": "selenium",
        "url": "https://www.netgear.com/about/security/",
        "Xpath": {
            "article": "//tbody[@id='tbSecurityUpdates']/tr[td[a]]",
            "date": ".//td[1]/a",
            "title": ".//td[2]/a",
            "link": ".//td[2]/a[@href]",
        },
        "max_entries": 10,
        "date_formats": ["%m/%d/%Y"],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "Zoom Security Bulletin": {
        "method": "beautifulsoup",
        "url": "https://www.zoom.com/ja/trust/security-bulletin/",
        "selectors": {
            "rows": "table.cmp-table tbody tr.cmp-table__row",
            "title": "td:nth-child(2)",
            "link": "td:nth-child(1) a[href]",
            "date": "td:nth-child(5)",
        },
        "date_formats": ["%m/%d/%Y"],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "OpenSSL": {
        "method": "beautifulsoup",
        "url": "https://openssl-library.org/news/newslog/",
        "selectors": {
            "rows": "tr",
            "title": "td:nth-child(2)",
            "link": "td:nth-child(2) a[href]",
            "date": "td:nth-child(1)",
        },
        "date_formats": ["%d-%b-%Y"],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "Cisco Webex Security Advisories": {
        "method": "beautifulsoup",
        "url": "https://www.cisco.com/c/ja_jp/support/conferencing/webex-meeting-center/products-security-advisories-list.html#~tab-documentation",
        "selectors": {
            "rows": "ul.listing li ul.ungroup li",
            "title": "a",
            "link": "a[href]",
            "date": "span.content",
        },
        "date_formats": ["%d/%b/%Y"],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "Apache Release": {
        "method": "beautifulsoup",
        "url": "https://struts.apache.org/releases.html",
        "selectors": {
            "rows": "table.table-condensed > tbody > tr",
            "title": "td:nth-of-type(1)",
            "link": "td:nth-of-type(4) a",
            "date": "td:nth-of-type(2)",
        },
        "date_formats": ["%d %B %Y"],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "Apache Vulnerability": {
        "method": "beautifulsoup",
        "url": "https://struts.apache.org/releases.html",
        "selectors": {
            "rows": "table.table-condensed > tbody > tr",
            "title": "td:nth-of-type(3) a",
            "link": "td:nth-of-type(3) a",
            "date": "td:nth-of-type(2)",
        },
        "date_formats": ["%d %B %Y"],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "SKYSEA Client View": {
        "method": "beautifulsoup",
        "url": "https://www.skygroup.jp/security-info/",
        "selectors": {
            "rows": "div.newsContainer a.newsLine",
            "date": "p.newsLine__date",
            "title": "p.newsLine__title",
            "link": "a[href]",
        },
        "date_formats": ["%Y/%m/%d"],
        "max_entries": 20,
        "remove_words": [],
    },
    "Aruba": {
        "method": "rss",
        "url": "https://support.hpe.com/hpesc/public/api/document/sec_bull_rss_feed",
        "date_formats": [],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "BarracudaAdvisories": {
        "method": "beautifulsoup",
        "url": "https://www.barracuda.com/company/legal/security-advisory",
        "selectors": {
            "rows": "tr.cmp-table-row:not(.cmp-table__container__table__row--header)",
            "title": "td:nth-of-type(1) a",
            "link": "td:nth-of-type(1) a",
            "date": "td:nth-of-type(2) div",
        },
        "date_formats": ["%B %d, %Y"],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "FFRI Security Info": {
        "method": "beautifulsoup",
        "url": "https://www.ffri.jp/security-info",
        "selectors": {
            "rows": "ul.ir-list > li",
            "date": "span.date",
            "title": "span.infotxt > a",
            "link": "span.infotxt > a",
        },
        "date_formats": ["%Y.%m.%d"],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "SonicWall": {
        "method": "rss",
        "url": "https://psirtapi.global.sonicwall.com/api/v1/feed/rss.xml",
        "date_formats": [],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "Google Chrome Releases": {
        "method": "rss",
        "url": "https://feeds.feedburner.com/GoogleChromeReleases",
        "date_formats": ["%Y-%m-%dT%H:%M:%S.%f%z"],
        "filter_description_keywords": [],
        "filter_title_keywords": ["Stable", "Desktop"],
        "remove_words": [],
    },
    "Google Chrome Releases": {
        "method": "beautifulsoup",
        "url": "https://chromereleases.googleblog.com/search/label/Stable%20updates",
        "selectors": {
            "rows": "div.post",
            "title": ".title a",
            "link": ".title a[href]",
            "date": ".publishdate",
        },
        "date_formats": ["%A, %B %d, %Y"],
        "filter_title_keywords": ["Desktop"],
        "remove_words": [],
    },
    "Mozilla Security Advisories": {
        "method": "beautifulsoup",
        "url": "https://www.mozilla.org/en-US/security/advisories/",
        "selectors": {
            "rows": "article h2",
            "link": "ul li.level-item a[href]",
            "title": "ul li.level-item a",
            "date": "h2",
        },
        "date_formats": ["%B %d, %Y"],
        "max_entries": 20,
        "remove_words": [],
    },
    "Microsoft Edge": {
        "method": "rss",
        "url": "https://api.msrc.microsoft.com/update-guide/rss",
        "filter_description_keywords": ["Edge"],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "Microsoft Edge Security Updates": {
        "method": "beautifulsoup",
        "url": "https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnotes-security",
        "selectors": {
            "date": "div.heading-wrapper > h2",
            "link": "a[href]",
            "description": "p",
            "cve": "ul li a[href]",
        },
        "title": "Microsoft Edge Security Updates",
        "date_formats": ["%B %d, %Y"],
        "remove_words": [],
    },
    "Microsoft Teams": {
        "method": "rss",
        "url": "https://api.msrc.microsoft.com/update-guide/rss",
        "filter_description_keywords": ["Teams"],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "MS月例": {
        "method": "rss",
        "url": "https://msrc.microsoft.com/blog/categories/japan-security-team/feed",
        "filter_description_keywords": [],
        "filter_title_keywords": ["セキュリティ更新プログラム"],
        "remove_words": [],
    },
    "TrendMicro Apex One": {
        "method": "rss",
        "url": "http://feeds.trendmicro.com/jp/SupportNews",
        "filter_description_keywords": [],
        "filter_title_keywords": [
            "アドバイザリ",
            "Critical",
            "Patch",
            "脆弱性",
        ],
        "remove_words": [],
    },
    "Palo Alto": {
        "method": "rss",
        "url": "https://security.paloaltonetworks.com/rss.xml",
        "filter_description_keywords": [],
        "filter_title_keywords": ["CRITICAL", "HIGH", "MEDIUM"],
        "remove_words": [],
    },
    "FORTINET": {
        "method": "rss",
        "url": "https://filestore.fortinet.com/fortiguard/rss/ir.xml",
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "Ivanti": {
        "method": "rss",
        "url": "https://www.ivanti.com/blog/topics/security-advisory/rss",
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "ShareFile": {
        "method": "rss",
        "url": "https://status.sharefile.com/history.rss",
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "EmEditor": {
        "method": "rss",
        "url": "https://jp.emeditor.com/blog/feed/",
        "filter_description_keywords": [],
        "filter_title_keywords": ["EmEditor", "脆弱性", "CVE"],
        "remove_words": [],
    },
    "WordPress": {
        "method": "rss",
        "url": "https://wordpress.org/news/category/security/feed/",
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "Apple": {
        "method": "beautifulsoup",
        "url": "https://support.apple.com/en-us/100100",
        "selectors": {
            "rows": "tr",
            "title": "td:nth-child(1) a",
            "link": "td:nth-child(1) a",
            "date": "td:nth-child(3) p",
        },
        "date_formats": ["%B %d, %Y"],
        "filter_description_keywords": [],
        "filter_title_keywords": ["iOS", "macOS", "iPadOS"],
        "remove_words": [],
    },
    "Android OS": {
        "method": "beautifulsoup",
        "url": "https://source.android.com/docs/security/bulletin/asb-overview",
        "selectors": {
            "rows": "tr",
            "title": "td:nth-child(1) a",
            "link": "td:nth-child(1) a",
            "date": "td:nth-child(3)",
            "period": "td:nth-child(4)",
        },
        "date_formats": ["%B %d, %Y"],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "AtlassianAdvisories": {
        "method": "beautifulsoup",
        "url": "https://confluence.atlassian.com/security/security-advisories-bulletins-1236937381.html",
        "selectors": {
            "rows": "div.page-sidepanel.sidepanel-in-this-section ul li",
            "title": "a",
            "link": "a",
            "date": "a",
        },
        "date_formats": [],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "BIND": {
        "method": "rss",
        "url": "https://kb.isc.org/v1/rss/en",
        "date_formats": ["%a, %d %b %Y %H:%M:%S %z"],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "Proself": {
        "method": "rss",
        "url": "https://www.proself.jp/category-information/all/feed/",
        "filter_description_keywords": [],
        "filter_title_keywords": ["重要"],
        "remove_words": [],
    },
    "Oracle": {
        "method": "rss",
        "url": "https://www.oracle.com/ocom/groups/public/@otn/documents/webcontent/rss-otn-sec.xml",
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "date_formats": ["%a, %d %b %Y %H:%M:%S %z"],
        "remove_words": [],
    },
    "SolarWinds": {
        "method": "rss",
        "url": "https://www.solarwinds.com/shared-content/rss-feed/solarwinds-cve-rss-feed.xml",
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "CheckPoint": {
        "method": "rss",
        "url": "https://advisories.checkpoint.com/advisories/feed",
        "filter_description_keywords": [
            "CloudGuard",
            "Quantum",
            "Check Point",
            "Spark",
        ],
        "filter_title_keywords": [],
        "remove_words": ["appeared first on Check Point Software"],
    },
    "QNAP Systems": {
        "method": "rss",
        "url": "https://www.qnap.com/en-us/security-advisory/feed",
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "F5": {
        "method": "rss",
        "url": "https://support.apis.f5.com/articles/rss/v4/feed?apikey=aIy8F8CUfdgqXPv6pHJ0RU64GQiYiyUK&page=1&results=10&source=kbarticles&source=techcomm&documentType=Security%20Advisory&lastPublishedDateStart=2025-01-15&firstPublishedDateEnd=2025-01-15&requestid=2b17d192-31e2-4b1b-a956-7e644d9651d9",
        "filter_description_keywords": [],
        "filter_title_keywords": [
            "Overview of F5 vulnerabilities",
            "Overview of Quarterly Security Notifications",
        ],
        "remove_words": [],
    },
    "NGINX": {
        "method": "beautifulsoup",
        "url": "https://nginx.org/news.html",
        "selectors": {
            "rows": "tr",
            "date": "td.date",
            "title": "td p a",
            "description": "td p",
            "link": "td p a[href]",
        },
        "date_formats": ["%Y-%m-%d"],
        "filter_description_keywords": [],
        "filter_title_keywords": ["CVE"],
        "remove_words": [],
    },
    "MovableType": {
        "method": "rss",
        "url": "https://www.sixapart.jp/movabletype/news/atom.xml",
        "filter_description_keywords": [],
        "filter_title_keywords": ["脆弱性", "CVE"],
        "remove_words": [],
    },
    "Joomla!": {
        "method": "rss",
        "url": "https://developer.joomla.org/security-centre.feed?type=rss",
        "filter_description_keywords": ["CVE"],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "PHPMailer GitHub": {
        "method": "beautifulsoup",
        "url": "https://github.com/PHPMailer/PHPMailer/security/advisories",
        "selectors": {
            "rows": "li.Box-row",
            "title": "a.Link--primary",
            "link": "a.Link--primary[href]",
            "date": "relative-time",
            "severity": "span.Label",
        },
        "date_formats": ["%b %d, %Y"],
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    "NTP Release": {
        "method": "beautifulsoup",
        "url": "https://www.ntp.org/dev/releasetimeline/",
        "selectors": {
            "rows": "table tr",
            "date": "td:nth-of-type(1)",
            "title": "td:nth-of-type(2) a",
            "link": "td:nth-of-type(2) a[href]",
        },
        "date_formats": ["%Y %b %d"],
        "max_entries": 10,
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "remove_words": [],
    },
    # Security Advisaryはメール取得?
    "GNU C Library (glibc) Releases": {
        "method": "beautifulsoup",
        "url": "https://sourceware.org/glibc/",
        # "selectors": {
        #     "rows": "div#centercontent p",  # ニュース情報が含まれる <p> 要素
        #     "date": "p",  # ニュースの日付情報（"2024-07-22" 形式）
        #     "title": "p a",  # ニュースタイトル
        #     "link": "p a[href]",  # ニュースリンク
        # },
        "date_formats": ["%Y-%m-%d"],  # 日付フォーマット
        "filter_description_keywords": [],
        "filter_title_keywords": [],
        "max_entries": 20,
        "remove_words": [],
    },
    "Postfix": {
        "method": "beautifulsoup",
        "url": "http://www.postfix.org/announcements.html",
        "selectors": {
            "rows": "p",
            "date": "p",
            "title": "a",
            "link": "a[href]",
        },
        "date_formats": ["%B %d, %Y"],
        "max_entries": 10,
        "remove_words": [],
    },
}

# ファイルパス設定
BASE_PATH = (
    r"vulnerability_data"
)
LATEST_FILE = r"latest_vulnerability.csv"
LATEST_ENTRIES_FILE = r"latest_site_entries.csv"
FILTERED_FILE = r"filtered_articles.csv"
EXCEL_FILE = r"FilterVulnerability.xlsx"
LOG_FILE = r"vulnerability_logger.log"

HEADERS = {
    "User-Agent": "Mozilla/5.0"
}

# タイムゾーン情報
TZINFOS = {
    "PST": gettz("America/Los_Angeles"),
    "PDT": gettz("America/Los_Angeles"),
}