name: Update RSS Feed

on:
  #   schedule:
  # 平日 09:00 ～ 17:00 は 20分に1回
  # - cron: "*/20 9-17 * * 1-5"

  workflow_dispatch: # 手動実行も可能

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: 依存パッケージをインストール (キャッシュを利用)
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 依存パッケージをインストール
        run: pip install -r requirements.txt

      - name: データ収集＆RSS生成
        run: python main.py

      - name: Commit & Push RSS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add rss.xml
          git commit -m "Update RSS feed" || exit 0
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
