name: Update RSS Feed

on:
  schedule:
    # 平日 (月曜〜金曜) の 08:30 〜 19:30 は 5分に1回実行
    - cron: "*/5 8-19 * * 1-5"

    # それ以外 (平日の 0:00〜8:25 & 19:35〜23:55, 土日) は1時間に1回実行
    - cron: "0,30 * * * *"

  workflow_dispatch: # 手動実行も可能

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: 依存パッケージをインストール
        run: pip install -r requirements.txt

      - name: データ収集＆RSS生成
        run: python main.py

      - name: Commit & Push RSS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add rss.xml
          git commit -m "Update RSS feed" || exit 0
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
